
admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

cp:
    resource: "@CPBundle/Resources/config/routing.yml"
    prefix:   /



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

