<?php

namespace CP\CPBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaRepository extends EntityRepository
{
    public function getNumberEntities()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u');

        return count($qb->getQuery()->getResult());
    }

    public function getAgenda()
    {
        $now = new \DateTime();

        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.date >= :date')
            ->orderBy('u.date', 'DESC')
            ->setParameter('date', $now);
           // ->setMaxResults(1);

        //var_dump($qb->getQuery()->getResult());
        return $qb->getQuery()->getResult();
    }

}
