<?php

namespace CP\CPBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{

}
