services:
    admin.twig.admin_extension:
        class: CP\CPBundle\Twig\AdminExtension
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }